# Generated by Django 5.2.3 on 2025-06-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
