# Generated by Django 5.2.3 on 2025-06-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
